### ISSUE TITLE
You may want to take a look at MimeKit

### ISSUE THREAD

**Issue by jstedfast** [butlersoftware/Mime#1]
You may want to consider looking into [MimeKit](https://github.com/jstedfast/MimeKit) instead of duplicating all of the effort involved. It seems you've already got a fair bit of code, but it's almost a guarantee that you'll find that MimeKit handles edge cases that you haven't even considered yet.

Seems like this code was auto-generated? I think you'll find that the MimeKit source code is very clean and easy to understand while also exceptionally fast - there's no other .NET MIME parser that comes close.

It's also MIT licensed, so there's no issues with you using it in a commercial setting.

I wish you luck either way, but I really hope you consider using MimeKit. It will save you a lot of effort.

**Comment by fnrhombus** [comment]
Haha actually it's decompiled strait out of some binaries that I found buried in the Microsoft Exchange setup iso from MSDN. All I've done is run some Resharper refactorings to change the namespaces and code style to my liking. Therefore, it is my expectation that all the edge cases are well covered.

It looks super robust and I admit is way overkill for my needs, but on the other hand it's not broken and there's no pressure on me to actually support this beast.

Should I ever find myself with some new billable time on the relevant project, I'll definitely check out your stuff before I even think about actually diving in to this code base. Thanks for the invite!
